language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
before_install:
- chmod +x gradlew
- gem install rake
deploy:
  provider: releases
  api_key:
    secure:
  file: build/libs/xlr-msteams-plugin.jar
  skip_cleanup: true
  on:
    tags: true
    repo: AkshatParmar/xlr-teams-plugin
  notifications:
    teams:
      secure: