language: java
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure:
  file: build/libs/xlr-msteams-plugin.jar
  skip_cleanup: true
  on:
    tags: true
    repo: AkshatParmar/xlr-teams-plugin
  notifications:
    teams:
      secure: